export const BOOKS = {
  old: [
    { id: "GEN", name: "Genesis", chapters: 50, author: "Moses (traditionally)", date: "~1440–1400 BC", genre: "Law/Narrative", testament: "OT" },
    { id: "EXO", name: "Exodus", chapters: 40, author: "Moses", date: "~1440–1400 BC", genre: "Law/Narrative", testament: "OT" },
    { id: "LEV", name: "Leviticus", chapters: 27, author: "Moses", date: "~1440–1400 BC", genre: "Law", testament: "OT" },
    { id: "NUM", name: "Numbers", chapters: 36, author: "Moses", date: "~1440–1400 BC", genre: "Law/Narrative", testament: "OT" },
    { id: "DEU", name: "Deuteronomy", chapters: 34, author: "Moses", date: "~1400 BC", genre: "Law", testament: "OT" },
    { id: "JOS", name: "Joshua", chapters: 24, author: "Joshua", date: "~1350 BC", genre: "Narrative", testament: "OT" },
    { id: "JDG", name: "Judges", chapters: 21, author: "Samuel (traditionally)", date: "~1050 BC", genre: "Narrative", testament: "OT" },
    { id: "RUT", name: "Ruth", chapters: 4, author: "Unknown (possibly Samuel)", date: "~1000 BC", genre: "Narrative", testament: "OT" },
    { id: "1SA", name: "1 Samuel", chapters: 31, author: "Samuel, Nathan, Gad", date: "~930 BC", genre: "Narrative", testament: "OT" },
    { id: "2SA", name: "2 Samuel", chapters: 24, author: "Nathan, Gad", date: "~930 BC", genre: "Narrative", testament: "OT" },
    { id: "1KI", name: "1 Kings", chapters: 22, author: "Jeremiah (traditionally)", date: "~560 BC", genre: "Narrative", testament: "OT" },
    { id: "2KI", name: "2 Kings", chapters: 25, author: "Jeremiah (traditionally)", date: "~560 BC", genre: "Narrative", testament: "OT" },
    { id: "1CH", name: "1 Chronicles", chapters: 29, author: "Ezra (traditionally)", date: "~450 BC", genre: "Narrative", testament: "OT" },
    { id: "2CH", name: "2 Chronicles", chapters: 36, author: "Ezra (traditionally)", date: "~450 BC", genre: "Narrative", testament: "OT" },
    { id: "EZR", name: "Ezra", chapters: 10, author: "Ezra", date: "~440 BC", genre: "Narrative", testament: "OT" },
    { id: "NEH", name: "Nehemiah", chapters: 13, author: "Nehemiah", date: "~430 BC", genre: "Narrative", testament: "OT" },
    { id: "EST", name: "Esther", chapters: 10, author: "Unknown (possibly Mordecai)", date: "~470 BC", genre: "Narrative", testament: "OT" },
    { id: "JOB", name: "Job", chapters: 42, author: "Unknown (possibly Moses)", date: "Unknown (~2000–500 BC)", genre: "Wisdom/Poetry", testament: "OT" },
    { id: "PSA", name: "Psalms", chapters: 150, author: "David, Asaph, Sons of Korah, others", date: "~1400–400 BC", genre: "Poetry/Worship", testament: "OT" },
    { id: "PRO", name: "Proverbs", chapters: 31, author: "Solomon, Agur, Lemuel", date: "~970–700 BC", genre: "Wisdom", testament: "OT" },
    { id: "ECC", name: "Ecclesiastes", chapters: 12, author: "Solomon (traditionally)", date: "~935 BC", genre: "Wisdom", testament: "OT" },
    { id: "SNG", name: "Song of Solomon", chapters: 8, author: "Solomon", date: "~960 BC", genre: "Poetry", testament: "OT" },
    { id: "ISA", name: "Isaiah", chapters: 66, author: "Isaiah", date: "~740–680 BC", genre: "Prophecy", testament: "OT" },
    { id: "JER", name: "Jeremiah", chapters: 52, author: "Jeremiah", date: "~627–585 BC", genre: "Prophecy", testament: "OT" },
    { id: "LAM", name: "Lamentations", chapters: 5, author: "Jeremiah", date: "~586 BC", genre: "Poetry", testament: "OT" },
    { id: "EZK", name: "Ezekiel", chapters: 48, author: "Ezekiel", date: "~593–571 BC", genre: "Prophecy", testament: "OT" },
    { id: "DAN", name: "Daniel", chapters: 12, author: "Daniel", date: "~536 BC", genre: "Prophecy/Narrative", testament: "OT" },
    { id: "HOS", name: "Hosea", chapters: 14, author: "Hosea", date: "~750–715 BC", genre: "Prophecy", testament: "OT" },
    { id: "JOL", name: "Joel", chapters: 3, author: "Joel", date: "~835–800 BC", genre: "Prophecy", testament: "OT" },
    { id: "AMO", name: "Amos", chapters: 9, author: "Amos", date: "~760–750 BC", genre: "Prophecy", testament: "OT" },
    { id: "OBA", name: "Obadiah", chapters: 1, author: "Obadiah", date: "~586 BC", genre: "Prophecy", testament: "OT" },
    { id: "JON", name: "Jonah", chapters: 4, author: "Jonah", date: "~760 BC", genre: "Narrative", testament: "OT" },
    { id: "MIC", name: "Micah", chapters: 7, author: "Micah", date: "~735–700 BC", genre: "Prophecy", testament: "OT" },
    { id: "NAM", name: "Nahum", chapters: 3, author: "Nahum", date: "~663–612 BC", genre: "Prophecy", testament: "OT" },
    { id: "HAB", name: "Habakkuk", chapters: 3, author: "Habakkuk", date: "~609–605 BC", genre: "Prophecy", testament: "OT" },
    { id: "ZEP", name: "Zephaniah", chapters: 3, author: "Zephaniah", date: "~630 BC", genre: "Prophecy", testament: "OT" },
    { id: "HAG", name: "Haggai", chapters: 2, author: "Haggai", date: "~520 BC", genre: "Prophecy", testament: "OT" },
    { id: "ZEC", name: "Zechariah", chapters: 14, author: "Zechariah", date: "~520–480 BC", genre: "Prophecy", testament: "OT" },
    { id: "MAL", name: "Malachi", chapters: 4, author: "Malachi", date: "~430 BC", genre: "Prophecy", testament: "OT" },
  ],
  new: [
    { id: "MAT", name: "Matthew", chapters: 28, author: "Matthew (Levi)", date: "~55–65 AD", genre: "Gospel", testament: "NT" },
    { id: "MRK", name: "Mark", chapters: 16, author: "John Mark", date: "~55–70 AD", genre: "Gospel", testament: "NT" },
    { id: "LUK", name: "Luke", chapters: 24, author: "Luke", date: "~59–63 AD", genre: "Gospel", testament: "NT" },
    { id: "JHN", name: "John", chapters: 21, author: "John (the Apostle)", date: "~85–95 AD", genre: "Gospel", testament: "NT" },
    { id: "ACT", name: "Acts", chapters: 28, author: "Luke", date: "~63–70 AD", genre: "Narrative", testament: "NT" },
    { id: "ROM", name: "Romans", chapters: 16, author: "Paul", date: "~57 AD", genre: "Epistle", testament: "NT" },
    { id: "1CO", name: "1 Corinthians", chapters: 16, author: "Paul", date: "~55 AD", genre: "Epistle", testament: "NT" },
    { id: "2CO", name: "2 Corinthians", chapters: 13, author: "Paul", date: "~56 AD", genre: "Epistle", testament: "NT" },
    { id: "GAL", name: "Galatians", chapters: 6, author: "Paul", date: "~49–55 AD", genre: "Epistle", testament: "NT" },
    { id: "EPH", name: "Ephesians", chapters: 6, author: "Paul", date: "~60–62 AD", genre: "Epistle", testament: "NT" },
    { id: "PHP", name: "Philippians", chapters: 4, author: "Paul", date: "~61–62 AD", genre: "Epistle", testament: "NT" },
    { id: "COL", name: "Colossians", chapters: 4, author: "Paul", date: "~60–62 AD", genre: "Epistle", testament: "NT" },
    { id: "1TH", name: "1 Thessalonians", chapters: 5, author: "Paul", date: "~51 AD", genre: "Epistle", testament: "NT" },
    { id: "2TH", name: "2 Thessalonians", chapters: 3, author: "Paul", date: "~51–52 AD", genre: "Epistle", testament: "NT" },
    { id: "1TI", name: "1 Timothy", chapters: 6, author: "Paul", date: "~63–65 AD", genre: "Epistle", testament: "NT" },
    { id: "2TI", name: "2 Timothy", chapters: 4, author: "Paul", date: "~66–67 AD", genre: "Epistle", testament: "NT" },
    { id: "TIT", name: "Titus", chapters: 3, author: "Paul", date: "~63–65 AD", genre: "Epistle", testament: "NT" },
    { id: "PHM", name: "Philemon", chapters: 1, author: "Paul", date: "~60–62 AD", genre: "Epistle", testament: "NT" },
    { id: "HEB", name: "Hebrews", chapters: 13, author: "Unknown (Paul, Apollos, or Barnabas)", date: "~64–68 AD", genre: "Epistle", testament: "NT" },
    { id: "JAS", name: "James", chapters: 5, author: "James (brother of Jesus)", date: "~45–49 AD", genre: "Epistle", testament: "NT" },
    { id: "1PE", name: "1 Peter", chapters: 5, author: "Peter", date: "~62–64 AD", genre: "Epistle", testament: "NT" },
    { id: "2PE", name: "2 Peter", chapters: 3, author: "Peter", date: "~65–68 AD", genre: "Epistle", testament: "NT" },
    { id: "1JN", name: "1 John", chapters: 5, author: "John", date: "~85–95 AD", genre: "Epistle", testament: "NT" },
    { id: "2JN", name: "2 John", chapters: 1, author: "John", date: "~85–95 AD", genre: "Epistle", testament: "NT" },
    { id: "3JN", name: "3 John", chapters: 1, author: "John", date: "~85–95 AD", genre: "Epistle", testament: "NT" },
    { id: "JUD", name: "Jude", chapters: 1, author: "Jude (brother of Jesus)", date: "~65–80 AD", genre: "Epistle", testament: "NT" },
    { id: "REV", name: "Revelation", chapters: 22, author: "John", date: "~95 AD", genre: "Apocalyptic/Prophecy", testament: "NT" },
  ],
};

export const ALL_BOOKS = [...BOOKS.old, ...BOOKS.new];
